/**
 * This program prompts a user to enter a number between 1 and N
 * and then enter the max number of guesses to guess a number between 1 and N
 * if the guessed number is higher it will display "too high"
 * if the guessed number is lower it will display "too low"
 * if the guessed number is correct it will display "correct!"
 * @author Aanvi Guliani
 * @version 1.0
 */

import java.util.Scanner;

public class Unit4Lab1 
{
	public static void main( String [] args )
	{
		//prompt user to enter number of maximum guesses
		System.out.print("How many guesses would you like? ");
		Scanner inputmaxg = new Scanner(System.in);
		int numqguesses = inputmaxg.nextInt();
		
		//prompt user to enter max number
		System.out.print("Pick a number N ");
		Scanner inputnum = new Scanner(System.in);
		int maxnumber = inputnum.nextInt();
		
		//Random number that user will guess
		int randomNumber = 0;
		randomNumber = (int) ( maxnumber * Math.random() ) + 1;
		// For testing: System.out.println("Random Number generated by program: " +randomNumber);
		
		// initialize loop variables
		int successfultry = 0;
		int i = 1;
		
		//loop for user to guess
		        while (i <= numqguesses)
				{
					//Prompt user to enter guess
					System.out.print("Guess a number between 1 and " + maxnumber);
					Scanner inputg = new Scanner(System.in);
					int guess = inputg.nextInt();
					// Check if the guess is correct - print message, set success flag and break from the loop
					// Continue loop if incorrect
					if (guess == randomNumber) 
					{
						System.out.println("Correct");
						successfultry = 1;
						break;
					}
					
					else if (guess < randomNumber)
					{
						System.out.println("Too low.");
					}
					else 
					{
						System.out.println("Too high.");
					}
					i++;
				}
		        //check if user guessed correctly. If not, print the message
		        if (successfultry == 0) 
                {
				System.out.println("Sorry, you've exceeded the maximum number of guesses.");
                }
		}
		
	}
